### ISSUE TITLE
Implement NVIM plugin

### ISSUE THREAD

**Issue by simerplaha** [alephium/ralph-lsp#164]
Currently, our [NVIM support](https://github.com/alephium/ralph-lsp/tree/1b6be1ed32cc848fa15d85fde5c462401750722e?tab=readme-ov-file#run-lsp-in-neovim) is script based. Implementing a plugin, similar to how we support [VSCode](https://github.com/alephium/ralph-lsp/tree/1b6be1ed32cc848fa15d85fde5c462401750722e?tab=readme-ov-file#install-vscode-plugin) and have supported [IntellIJ](https://github.com/alephium/ralph-lsp/tree/75a570d719bd2e5a1c997e0dadff9f1373cd8d05/plugin-intellij), would make it more convenient for NVIM users.

This issue, along with #93 for IntelliJ, would enable Ralph to be compatible with three popular IDEs.

@tdroxler, please correct me if I'm wrong here. I'm assuming a plugin for NVIM would be useful because there is one for metals.

**Comment by tdroxler** [comment]
I will dig a bit other lsp-servers used in nvim, usually configuring as we have in the README is the way to go, no need for a plugin.

Metals have a plugin because they need it for their non-LSP stuff (which breaks the concept of a protocol....) for example I use metals without their plugin, I just configure it the same way as ralph-lsp.

Nevertheless, we could maybe add it to the [plugin I made for the syntax](https://github.com/tdroxler/ralph.vim), maybe it won't hurt to have it there too and could ease the installation for some nvim users.

But for this we'll probably need `ralph-lsp` available as an executable
